### ISSUE TITLE
"unexpected keyword argument: visibility" on attempted Bazel build

### ISSUE THREAD

**Issue by pwws** [abseil/abseil-cpp#1270]
Hi,

I have tried to add abseil as a dependency to my project. I followed [the official tutorial on how to do this](https://abseil.io/docs/cpp/quickstart.html), just using a newer version of `abseil`.

This is what I added to my `WORKSPACE`:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# other dependencies ...

http_archive(
  name = "absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz"],
  strip_prefix = "abseil-cpp-20220623.1",
  sha256 = "91ac87d30cc6d79f9ab974c51874a704de9c2647c40f6932597329a282217ba8"
)

# used by absl
http_archive(
    name = "bazel_skylib",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz"],
    sha256 = "f7be3474d42aae265405a592bb7da8e171919d74c16f082a5457840f06054728",
)
```

When I try to build a target with `@absl//absl/time:time` as a dependency or build that lib directly with `bazel build @absl//absl/time:time` command, I get the following error:

```
ERROR: Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_user/feaafeaf3ae6967f05cf4a7aa3a87089/external/absl/absl/BUILD.bazel", line 100, column 29, in <toplevel>
                selects.config_setting_group(
        File "/home/user/.cache/bazel/_bazel_user/feaafeaf3ae6967f05cf4a7aa3a87089/external/bazel_skylib/lib/selects.bzl", line 79, column 5, in _config_setting_group
                def _config_setting_group(name, match_any = [], match_all = []):
Error: _config_setting_group() got unexpected keyword argument: visibility
ERROR: /home/user/.cache/bazel/_bazel_user/feaafeaf3ae6967f05cf4a7aa3a87089/external/absl/absl/time/BUILD.bazel:28:11: errors encountered resolving select() keys for @absl//absl/time:time
ERROR: Analysis of target '@absl//absl/time:time' failed; build aborted:

```

Could you please help me resolve this build problem? Is it a problem with my `WORKSPACE` or something's wrong with `absl` Bazel files?

**Comment by derekmauro** [comment]
We cannot offer help without a complete reproduction. Try filling out all the information in https://github.com/abseil/abseil-cpp/blob/master/.github/ISSUE_TEMPLATE/00-bug_report.md and including all code in your report.

**Comment by pwws** [comment]
I have found the problem when I was preparing the minimal reproducible example. Below, I'm providing the explanation of the problem and solution for those who find this issue in Google search.

For me, reordering of some rules in my `WORKSPACE` solved the problem. This is a minimal WORKSPACE, that fails the build:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

_RULES_BOOST_COMMIT = "652b21e35e4eeed5579e696da0facbe8dba52b1f"

http_archive(
    name = "com_github_nelhage_rules_boost",
    sha256 = "c1b8b2adc3b4201683cf94dda7eef3fc0f4f4c0ea5caa3ed3feffe07e1fb5b15",
    strip_prefix = "rules_boost-%s" % _RULES_BOOST_COMMIT,
    urls = [
        "https://github.com/nelhage/rules_boost/archive/%s.tar.gz" % _RULES_BOOST_COMMIT,
    ],
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# Here I had a rule calling "git_respository" loaded above.
# However, the problem occurs even when "git_repository" is not called - just loading it is enough to fail the build.

# used by absl
http_archive(
    name = "bazel_skylib",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz"],
    sha256 = "f7be3474d42aae265405a592bb7da8e171919d74c16f082a5457840f06054728",
)

http_archive(
  name = "absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz"],
  strip_prefix = "abseil-cpp-20220623.1",
  sha256 = "91ac87d30cc6d79f9ab974c51874a704de9c2647c40f6932597329a282217ba8"
)
```

And a simple `BUILD`

```
cc_binary(
    name = "main_test",
    srcs = ["main_test.cpp"],
    deps = [
        "@absl//absl/time"
    ]
)
```

With the above `WORKSPACE` and `BUILD`, `bazel :main_test` fails with the error from my original post.

After some investigation, I've found that rules from `com_github_nelhage_rules_boost` and from `@bazel_tools//tools/build_defs/repo:git.bzl` use `bazel_skylib` in a different version than `1.2.1` that I import for abseil.

After moving `bazel_skylib` import to the top of the `WORKSPACE`, the build succeeded:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# used by absl
# must come before the Boost rules and load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
http_archive(
    name = "bazel_skylib",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz"],
    sha256 = "f7be3474d42aae265405a592bb7da8e171919d74c16f082a5457840f06054728",
)

_RULES_BOOST_COMMIT = "652b21e35e4eeed5579e696da0facbe8dba52b1f"

http_archive(
    name = "com_github_nelhage_rules_boost",
    sha256 = "c1b8b2adc3b4201683cf94dda7eef3fc0f4f4c0ea5caa3ed3feffe07e1fb5b15",
    strip_prefix = "rules_boost-%s" % _RULES_BOOST_COMMIT,
    urls = [
        "https://github.com/nelhage/rules_boost/archive/%s.tar.gz" % _RULES_BOOST_COMMIT,
    ],
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
  name = "absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz"],
  strip_prefix = "abseil-cpp-20220623.1",
  sha256 = "91ac87d30cc6d79f9ab974c51874a704de9c2647c40f6932597329a282217ba8"
)
```
