### ISSUE TITLE
[Bug]: AddressSanitizer error using flat_hash_set

### ISSUE THREAD

**Issue by mdf-observe** [abseil/abseil-cpp#1601]
### Describe the issue

The following program under clang `-fsanitize=address` reliably hits an asan error:
```
#include "absl/container/flat_hash_set.h"

#include <iostream>

int main()
{
    absl::flat_hash_set<int> foo;
    auto iter = foo.begin();
    std::cerr << (iter == foo.end() ? 0 : *iter) << '\n';

    return 0;
}
```

The reported error:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==50604==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x555a827d057e bp 0x7fffd35d11b0 sp 0x7fffd35d1170 T0)
==50604==The signal is caused by a READ memory access.
==50604==Hint: address points to the zero page.
    #0 0x555a827d057e in absl::lts_20230802::container_internal::HashSetIteratorGenerationInfoEnabled::HashSetIteratorGenerationInfoEnabled(unsigned char const*) (/home/dev/.cache/bazel/_bazel_dev/879887c5836fdaf979328e5ec66360ff/execroot/_main/bazel-out/k8-fastbuild/bin/absl/container/xxxmdf+0x11b57e) (BuildId: 116bf94ac213cb3a)
    #1 0x555a827d0438 in absl::lts_20230802::container_internal::raw_hash_set<absl::lts_20230802::container_internal::FlatHashSetPolicy<int>, absl::lts_20230802::hash_internal::Hash<int>, std::equal_to<int>, std::allocator<int>>::iterator::iterator(absl::lts_20230802::container_internal::ctrl_t*, int*, unsigned char const*) (/home/dev/.cache/bazel/_bazel_dev/879887c5836fdaf979328e5ec66360ff/execroot/_main/bazel-out/k8-fastbuild/bin/absl/container/xxxmdf+0x11b438) (BuildId: 116bf94ac213cb3a)
    #2 0x555a827cffd9 in absl::lts_20230802::container_internal::raw_hash_set<absl::lts_20230802::container_internal::FlatHashSetPolicy<int>, absl::lts_20230802::hash_internal::Hash<int>, std::equal_to<int>, std::allocator<int>>::iterator_at(unsigned long) (/home/dev/.cache/bazel/_bazel_dev/879887c5836fdaf979328e5ec66360ff/execroot/_main/bazel-out/k8-fastbuild/bin/absl/container/xxxmdf+0x11afd9) (BuildId: 116bf94ac213cb3a)
    #3 0x555a827cdbb3 in absl::lts_20230802::container_internal::raw_hash_set<absl::lts_20230802::container_internal::FlatHashSetPolicy<int>, absl::lts_20230802::hash_internal::Hash<int>, std::equal_to<int>, std::allocator<int>>::begin() (/home/dev/.cache/bazel/_bazel_dev/879887c5836fdaf979328e5ec66360ff/execroot/_main/bazel-out/k8-fastbuild/bin/absl/container/xxxmdf+0x118bb3) (BuildId: 116bf94ac213cb3a)
    #4 0x555a827cd855 in main (/home/dev/.cache/bazel/_bazel_dev/879887c5836fdaf979328e5ec66360ff/execroot/_main/bazel-out/k8-fastbuild/bin/absl/container/xxxmdf+0x118855) (BuildId: 116bf94ac213cb3a)
    #5 0x7f9b3b12a082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: eebe5d5f4b608b8a53ec446b63981bba373ca0ca)
    #6 0x555a8270e94d in _start (/home/dev/.cache/bazel/_bazel_dev/879887c5836fdaf979328e5ec66360ff/execroot/_main/bazel-out/k8-fastbuild/bin/absl/container/xxxmdf+0x5994d) (BuildId: 116bf94ac213cb3a)
```

This program passes when using gcc or not using `-fsanitize=address`

### Steps to reproduce the problem

I used the following in a BUILD.bazel:
```
cc_binary(
    name = "asan_err",
    srcs = ["asan_err.cpp"],
    copts = [
        "-fsanitize=address",
    ],
    linkopts = [
        "-fsanitize=address",
    ],
    deps = [
        ":flat_hash_set",
    ],
)
```

I then ran `CC=/usr/bin/clang-15 bazel run absl/container:asan_err`.  The stock clang-12 with ubuntu 20.04 fails in the same way.

### What version of Abseil are you using?

Fails on 20240116.rc1 and 20230802.1 and 20230125.3

### What operating system and version are you using?

Ubuntu 20.04

### What compiler and version are you using?

Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64

### What build system are you using?

bazel 7.0.1

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-abi-and-why-dont-you-recommend-using-a-pre-compiled-version-of-abseil

This is a mixed-mode build. Part of the code is being build with ASAN, and part of it is not, causing the issue you see.

Instead, try `bazel build --copt=-fsanitize=address --linkopt=-fsanitize=address //path/to:target` to apply the flags globally to the build.
