### ISSUE TITLE
Won't build  for ios. 

### ISSUE THREAD

**Issue by mpalczew** [abseil/abseil-cpp#395]
bazel build --apple_platform_type=ios ...

ERROR: /Users/michalpalczewski/src/abseil-cpp/absl/debugging/BUILD.bazel:226:1: C++ compilation of rule '//absl/debugging:leak_check_api_enabled_for_testing' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote ... (remaining 19 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: invalid version number in '-mmacosx-version-min=13.1'

**Comment by trybka** [comment]
I believe you need to set `--cpu` as well.

Bazel defaults to building for Darwin (macOS) on a Mac, and changing `--apple_platform_type` is not always sufficient to target iOS.

Something like:
```
# For Device
--ios_multi_cpus=armv7,arm64
# For Simulator
--ios_multi_cpus=x86,x86_64
```
oughta do it.

**Comment by mpalczew** [comment]
Thanks for the info, I did just try this.

```
$bazel build --apple_platform_type=ios --ios_multi_cpus=x86,x86_64 ...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/command.profile.gz'
INFO: Invocation ID: 604481dd-f5cd-4c2a-8e60-f04bfcc98b40
INFO: Call stack for the definition of repository 'remote_java_tools_darwin' which is a http_archive (rule definition at /private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:280:1
INFO: Repository 'remote_java_tools_darwin' used the following cache hits instead of downloading the corresponding file.
 * Hash 'f0c488dac18f18ab1a0d18bbd65288c7a128e90a24d9c16f65bd8243f79483a0' for https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_darwin-v6.1.zip
If the definition of 'remote_java_tools_darwin' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'remote_java_tools_darwin':
   java.io.IOException: Error extracting /private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/external/remote_java_tools_darwin/java_tools_javac11_darwin-v6.1.zip to /private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/external/remote_java_tools_darwin: null
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_cc//:toolchain BuildConfigurationValue.Key[aeaa74887cfe38e00a8b2e6cfde0e537] false' (requested by nodes '//external:cc_toolchain BuildConfigurationValue.Key[aeaa74887cfe38e00a8b2e6cfde0e537] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No supported apple platform registered for target cpu ios_x86
	at com.google.devtools.build.lib.rules.apple.ApplePlatform.forTargetCpu(ApplePlatform.java:168)
	at com.google.devtools.build.lib.rules.apple.ApplePlatform.forTarget(ApplePlatform.java:154)
	at com.google.devtools.build.lib.rules.apple.AppleConfiguration.getSingleArchPlatform(AppleConfiguration.java:255)
	at com.google.devtools.build.lib.rules.apple.cpp.AppleCcToolchain.computeCcToolchainVariables(AppleCcToolchain.java:76)
	at com.google.devtools.build.lib.rules.apple.cpp.AppleCcToolchain.lambda$getAdditionalBuildVariablesComputer$b9d1f694$1(AppleCcToolchain.java:69)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainProviderHelper.getBuildVariables(CcToolchainProviderHelper.java:405)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainProviderHelper.getCcToolchainProvider(CcToolchainProviderHelper.java:220)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:78)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:40)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:184)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:734)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:900)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:345)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
	... 7 more

INFO: Elapsed time: 5.198s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 917 targets configured)
    Fetching @remotejdk11_macos; fetching
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_cc//:toolchain BuildConfigurationValue.Key[aeaa74887cfe38e00a8b2e6cfde0e537] false' (requested by nodes '//external:cc_toolchain BuildConfigurationValue.Key[aeaa74887cfe38e00a8b2e6cfde0e537] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No supported apple platform registered for target cpu ios_x86
	at com.google.devtools.build.lib.rules.apple.ApplePlatform.forTargetCpu(ApplePlatform.java:168)
	at com.google.devtools.build.lib.rules.apple.ApplePlatform.forTarget(ApplePlatform.java:154)
	at com.google.devtools.build.lib.rules.apple.AppleConfiguration.getSingleArchPlatform(AppleConfiguration.java:255)
	at com.google.devtools.build.lib.rules.apple.cpp.AppleCcToolchain.computeCcToolchainVariables(AppleCcToolchain.java:76)
	at com.google.devtools.build.lib.rules.apple.cpp.AppleCcToolchain.lambda$getAdditionalBuildVariablesComputer$b9d1f694$1(AppleCcToolchain.java:69)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainProviderHelper.getBuildVariables(CcToolchainProviderHelper.java:405)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainProviderHelper.getCcToolchainProvider(CcToolchainProviderHelper.java:220)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:78)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:40)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:184)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:734)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:900)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:345)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_cc//:toolchain BuildConfigurationValue.Key[aeaa74887cfe38e00a8b2e6cfde0e537] false' (requested by nodes '//external:cc_toolchain BuildConfigurationValue.Key[aeaa74887cfe38e00a8b2e6cfde0e537] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No supported apple platform registered for target cpu ios_x86
	at com.google.devtools.build.lib.rules.apple.ApplePlatform.forTargetCpu(ApplePlatform.java:168)
	at com.google.devtools.build.lib.rules.apple.ApplePlatform.forTarget(ApplePlatform.java:154)
	at com.google.devtools.build.lib.rules.apple.AppleConfiguration.getSingleArchPlatform(AppleConfiguration.java:255)
	at com.google.devtools.build.lib.rules.apple.cpp.AppleCcToolchain.computeCcToolchainVariables(AppleCcToolchain.java:76)
	at com.google.devtools.build.lib.rules.apple.cpp.AppleCcToolchain.lambda$getAdditionalBuildVariablesComputer$b9d1f694$1(AppleCcToolchain.java:69)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainProviderHelper.getBuildVariables(CcToolchainProviderHelper.java:405)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainProviderHelper.getCcToolchainProvider(CcToolchainProviderHelper.java:220)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:78)
	at com.google.devtools.build.lib.rules.cpp.CcToolchainSuite.create(CcToolchainSuite.java:40)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:338)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:184)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:734)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:900)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:345)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstrFAILED: Build did NOT complete successfully (40 packages loaded, 917 targets configured)
    Fetching @remotejdk11_macos; fetching
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
```

**Comment by suertreus** [comment]
I'm not able to repro this problem.

> java.io.IOException: Error extracting /private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/external/remote_java_tools_darwin/java_tools_javac11_darwin-v6.1.zip to /private/var/tmp/_bazel_michalpalczewski/e93e0c8d65b867ebf0a5316dd75e1669/external/remote_java_tools_darwin: null

I think this is your problem.  The error message "null" is unhelpful, but maybe double-check whether your filesystem is full?  In any case, I think this is more of a Bazel problem than an Abseil problem, so you might have more luck there: https://github.com/bazelbuild/bazel/issues.
